services:

  # File browsing
  webdav:
    build:
      context: .
      dockerfile: webdav.dockerfile
      args:
        - OWNER_NAME=${USER_GROUP_NAME}
        - OWNER_ID=${USER_GROUP_ID}
        - CONFIG_FILE=nginx.conf
        - AUTH_FILE=.htpasswd
    container_name: webdav
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${WEBDAV_PORT}:80
    volumes:
      - ${ROOT_PATH}:/var/www/webdav:z
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1g

  # Torrent
  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_VER}
    container_name: transmission
    environment:
      - TZ=${TIMEZONE}
      - PUID=${USER_GROUP_ID}
      - PGID=${USER_GROUP_ID}
      - USER=${SERVICES_USER}
      - PASS=${SERVICES_PASS}
    volumes:
      - ${ROOT_PATH}${TRANSMISSION_CONFIG}:/config:z
      - ${ROOT_PATH}:/downloads:z
    ports:
      - ${TRANSMISSION_PORT}:9091
      - 55797:55797
      - 55797:55797/udp
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1g

  soulseek:
    image: slskd/slskd:${SOULSEEK_VER}
    container_name: soulseek
    user: ${USER_GROUP_ID}:${USER_GROUP_ID}
    environment:
      - TZ=${TIMEZONE}
      - SLSKD_REMOTE_CONFIGURATION=false
      - SLSKD_UPLOAD_SLOTS=10
      # Authentication for Soulseek network
      - SLSKD_SLSK_USERNAME=${SOULSEEK_USER}
      - SLSKD_SLSK_PASSWORD=${SOULSEEK_PASS}
      # Authentication for web interface
      - SLSKD_USERNAME=${SERVICES_USER}
      - SLSKD_PASSWORD=${SERVICES_PASS}
      # Directories
      - SLSKD_SHARED_DIR=/share
      - SLSKD_DOWNLOADS_DIR=/downloads
      - SLSKD_INCOMPLETE_DIR=/incomplete
    ports:
      - ${SOULSEEK_PORT}:5030
      - 50300:50300
    volumes:
      # - ${ROOT_PATH}${SOULSEEK_CONFIG}:/app:z
      - ${ROOT_PATH}${COMICS_DIR}:/share/comics:z
      - ${ROOT_PATH}${SERIES_DIR}:/share/series:z
      - ${ROOT_PATH}${MUSIC_DIR}:/share/music:z
      - ${ROOT_PATH}${TSUNDOKU_DIR}:/share/unsorted:z
      - ${ROOT_PATH}${WAREHOUSE_PATH}:/downloads:z
      - ${ROOT_PATH}${TEMP_PATH}:/incomplete:z

  # Comics and Books
  komga:
    image: gotson/komga:${KOMGA_VER}
    container_name: komga
    user: ${USER_GROUP_ID}:${USER_GROUP_ID}
    environment:
      - TZ=${TIMEZONE}
      - JAVA_TOOL_OPTIONS=-Xmx1g
    ports:
      - ${KOMGA_PORT}:25600
    volumes:
      # Config
      - ${ROOT_PATH}${KOMGA_CONFIG}:/config:z
      - ${ROOT_PATH}${COMICS_DIR}:/data/historietas:z
      # Content
      - ${ROOT_PATH}${BOOKS_DIR}:/data/libros:z
      - ${ROOT_PATH}${ARTBOOKS_DIR}:/data/artbooks:z
      - ${ROOT_PATH}${TSUNDOKU_LIBRARY_DIR}:/data/tsundoku:z
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1g
    healthcheck:
      test: [
          "CMD-SHELL",
          "exec 5<>/dev/tcp/localhost/25600 || exit 1"
        ]
      interval: 90s
      timeout: 15s
      start_period: 3m
      retries: 2

  # Series and music
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VER}
    container_name: jellyfin
    user: ${USER_GROUP_ID}:${USER_GROUP_ID}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      # Config
      - ${ROOT_PATH}${JELLYFIN_CONFIG}:/config:z
      - ${ROOT_PATH}${JELLYFIN_CACHE}:/cache:z
      # Content
      - ${ROOT_PATH}${MUSIC_DIR}:/media/musica:z
      - ${ROOT_PATH}${SERIES_DIR}:/media/series:z
      - ${ROOT_PATH}${TSUNDOKU_VIDEOS_DIR}:/media/tsundoku:z
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1g
    healthcheck:
      test: [
          "CMD-SHELL",
          "curl -f http://localhost:8096/health || exit 1"
        ]
      interval: 90s
      timeout: 15s
      start_period: 3m
      retries: 2
